<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Central Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="GREGORYJ01"><DocLocation><![CDATA[D:\PROJECT_FOLDER\Testscripts\ReviewMedications]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[ReviewMedications]]></DName>
<Res><![CDATA[Res4]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:04]]></Time>
<TimeTick>1447818604</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" status="Passed" Source="Action1" SourceLine="21" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:04]]></Time>
<TimeTick>1447818604</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Passed" Source="Action1" SourceLine="21" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:04]]></Time>
<TimeTick>1447818604</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="21" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Medications ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:09]]></Time>
<TimeTick>1447818609</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" >
<Disp><![CDATA[[ Medications ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Medications Management  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:21]]></Time>
<TimeTick>1447818621</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" Source="Action1" SourceLine="118" >
<Disp><![CDATA[[ Medications Management  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ Calcium Acetate (Phos Binder) Oral Tablet 667 MG ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:23]]></Time>
<TimeTick>1447818623</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" Source="Action1" SourceLine="131" >
<Disp><![CDATA[[ Calcium Acetate (Phos Binder) Oral Tablet 667 MG ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA["[ Calcium Acetate (Phos Binder) Oral Tablet 667 MG ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:23]]></Time>
<TimeTick>1447818623</TimeTick>
<NodeArgs eType="General" icon="8" nRep="22" >
<Disp><![CDATA["[ Calcium Acetate (Phos Binder) Oral Tablet 667 MG ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA["[ Calcium Acetate (Phos Binder) Oral Tablet 667 MG ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:23]]></Time>
<TimeTick>1447818623</TimeTick>
<NodeArgs eType="General" icon="8" nRep="23" >
<Disp><![CDATA["[ Calcium Acetate (Phos Binder) Oral Tablet 667 MG ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA["[ Calcium Acetate (Phos Binder) Oral Tablet 667 MG ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:23]]></Time>
<TimeTick>1447818623</TimeTick>
<NodeArgs eType="General" icon="8" nRep="24" >
<Disp><![CDATA["[ Calcium Acetate (Phos Binder) Oral Tablet 667 MG ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:23]]></Time>
<TimeTick>1447818623</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="26" Source="Action1" SourceLine="137" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[   Add ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:23]]></Time>
<TimeTick>1447818623</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="28" >
<Disp><![CDATA[[   Add ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[   Add ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:23]]></Time>
<TimeTick>1447818623</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="30" >
<Disp><![CDATA[[   Add ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[   ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:27]]></Time>
<TimeTick>1447818627</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" Source="Action1" SourceLine="171" >
<Disp><![CDATA[[   ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["11/10/2015"]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:48]]></Time>
<TimeTick>1447818648</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="47" Source="Action1" SourceLine="191" >
<Disp><![CDATA[[ WebEdit ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["11/10/2015"]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:49]]></Time>
<TimeTick>1447818649</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="50" Source="Action1" SourceLine="201" >
<Disp><![CDATA[[ WebEdit ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:53]]></Time>
<TimeTick>1447818653</TimeTick>
<NodeArgs eType="General" icon="10" nRep="51" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/17/2015 - 21:50:03" eTime="11/17/2015 - 21:50:53" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[ReviewMedications Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[11/17/2015 - 21:50:53]]></Time>
<TimeTick>1447818653</TimeTick>
<NodeArgs eType="General" icon="11" nRep="54" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/17/2015 - 21:50:02" eTime="11/17/2015 - 21:50:53" passed="3" failed="0" warnings="0" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test ReviewMedications Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>