<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="GREGORYJ"><DocLocation><![CDATA[D:\PROJECT_FOLDER\Testscripts\MedAdvisorWFprovider]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[MedAdvisorWFprovider]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[2/25/2016 - 15:54:43]]></Time>
<TimeTick>1456395883</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" status="Passed" Source="Action1" SourceLine="19" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[2/25/2016 - 15:54:43]]></Time>
<TimeTick>1456395883</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Passed" Source="Action1" SourceLine="19" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[2/25/2016 - 15:54:43]]></Time>
<TimeTick>1456395883</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="19" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2/25/2016 - 15:54:45]]></Time>
<TimeTick>1456395885</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Details>
<Time><![CDATA[2/25/2016 - 15:54:45]]></Time>
<TimeTick>1456395885</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="13" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ DaVita VillageHealth Capella ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:54:50]]></Time>
<TimeTick>1456395890</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" >
<Disp><![CDATA[[ DaVita VillageHealth Capella ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[  Internet Explorer ].Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:54:50]]></Time>
<TimeTick>1456395890</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[[  Internet Explorer ].Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].GetROProperty "visible"]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:55:11]]></Time>
<TimeTick>1456395911</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="61" status="Warning" >
<Disp><![CDATA[[ WebElement ].GetROProperty "visible"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ WebElement ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "[ WebElement ]" (of class WebElement). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2/25/2016 - 15:55:11]]></Time>
<TimeTick>1456395911</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ WebElement ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebElement<br>innerhtml = Loading config parameters...<br>Html Tag = SPAN<br>]]></Details>
<Time><![CDATA[2/25/2016 - 15:55:11]]></Time>
<TimeTick>1456395911</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="63" status="Warning" nType="Description" >
<Disp><![CDATA[[ WebElement ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="62" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ WebElement ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ DaVita VillageHealth Capella ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:55:11]]></Time>
<TimeTick>1456395911</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="66" >
<Disp><![CDATA[[ DaVita VillageHealth Capella ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ username ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 2000]]></Details>
<Time><![CDATA[2/25/2016 - 15:55:20]]></Time>
<TimeTick>1456395920</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="85" >
<Disp><![CDATA[[ username ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ username ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["PTC"]]></Details>
<Time><![CDATA[2/25/2016 - 15:55:20]]></Time>
<TimeTick>1456395920</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="87" >
<Disp><![CDATA[[ username ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["test123"]]></Details>
<Time><![CDATA[2/25/2016 - 15:55:20]]></Time>
<TimeTick>1456395920</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="89" >
<Disp><![CDATA[[ WebEdit ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["123123"]]></Details>
<Time><![CDATA[2/25/2016 - 15:55:20]]></Time>
<TimeTick>1456395920</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="91" >
<Disp><![CDATA[[ WebEdit ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[  Login  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:55:20]]></Time>
<TimeTick>1456395920</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="93" >
<Disp><![CDATA[[  Login  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].GetROProperty "visible"]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:55:50]]></Time>
<TimeTick>1456395950</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="139" status="Warning" >
<Disp><![CDATA[[ WebElement ].GetROProperty "visible"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ WebElement ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "[ WebElement ]" (of class WebElement). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2/25/2016 - 15:55:50]]></Time>
<TimeTick>1456395950</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ WebElement ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebElement<br>innerhtml = Authenticating...<br>Html Tag = SPAN<br>]]></Details>
<Time><![CDATA[2/25/2016 - 15:55:50]]></Time>
<TimeTick>1456395950</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="141" status="Warning" nType="Description" >
<Disp><![CDATA[[ WebElement ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="140" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ WebElement ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ DaVita VillageHealth Capella ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:56:24]]></Time>
<TimeTick>1456395984</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="144" >
<Disp><![CDATA[[ DaVita VillageHealth Capella ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/25/2016 - 15:56:37]]></Time>
<TimeTick>1456395997</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="170" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[      SIG   PAM   Balse, Sewell    (4)        SIG   PAM    Balse, Sewell    (4)     ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:56:44]]></Time>
<TimeTick>1456396004</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="175" >
<Disp><![CDATA[[      SIG   PAM   Balse, Sewell    (4)        SIG   PAM    Balse, Sewell    (4)     ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:56:44]]></Time>
<TimeTick>1456396004</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="177" >
<Disp><![CDATA[[ WebElement ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:56:44]]></Time>
<TimeTick>1456396004</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="179" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ (4)  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:56:47]]></Time>
<TimeTick>1456396007</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="182" >
<Disp><![CDATA[[ (4)  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ Meaney, Alford  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:56:49]]></Time>
<TimeTick>1456396009</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="185" >
<Disp><![CDATA[[ Meaney, Alford  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:56:55]]></Time>
<TimeTick>1456396015</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="189" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Finalize  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:56:58]]></Time>
<TimeTick>1456396018</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="192" >
<Disp><![CDATA[[ Finalize  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ Finalize  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:56:58]]></Time>
<TimeTick>1456396018</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="194" >
<Disp><![CDATA[[ Finalize  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ Finalize  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:01]]></Time>
<TimeTick>1456396021</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="196" >
<Disp><![CDATA[[ Finalize  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ Save  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:01]]></Time>
<TimeTick>1456396021</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="198" >
<Disp><![CDATA[[ Save  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ Close Patient Record? ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:04]]></Time>
<TimeTick>1456396024</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="201" >
<Disp><![CDATA[[ Close Patient Record? ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ Ok ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:04]]></Time>
<TimeTick>1456396024</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="204" >
<Disp><![CDATA[[ Ok ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ Ok ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:07]]></Time>
<TimeTick>1456396027</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="207" >
<Disp><![CDATA[[ Ok ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ Ok ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:07]]></Time>
<TimeTick>1456396027</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="209" >
<Disp><![CDATA[[ Ok ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:08]]></Time>
<TimeTick>1456396028</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="212" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ Finalize  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:09]]></Time>
<TimeTick>1456396029</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="215" >
<Disp><![CDATA[[ Finalize  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ Ok ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:10]]></Time>
<TimeTick>1456396030</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="217" >
<Disp><![CDATA[[ Ok ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ Ok ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:11]]></Time>
<TimeTick>1456396031</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="220" >
<Disp><![CDATA[[ Ok ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:17]]></Time>
<TimeTick>1456396037</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="225" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ Colbert, Mc  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:17]]></Time>
<TimeTick>1456396037</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="227" >
<Disp><![CDATA[[ Colbert, Mc  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:20]]></Time>
<TimeTick>1456396040</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="231" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ Finalize  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:23]]></Time>
<TimeTick>1456396043</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="234" >
<Disp><![CDATA[[ Finalize  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ Finalize  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:23]]></Time>
<TimeTick>1456396043</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="236" >
<Disp><![CDATA[[ Finalize  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ Finalize  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:27]]></Time>
<TimeTick>1456396047</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="238" >
<Disp><![CDATA[[ Finalize  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ Save  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:27]]></Time>
<TimeTick>1456396047</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="240" >
<Disp><![CDATA[[ Save  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ Close Patient Record? ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:30]]></Time>
<TimeTick>1456396050</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="243" >
<Disp><![CDATA[[ Close Patient Record? ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ Ok ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:30]]></Time>
<TimeTick>1456396050</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="246" >
<Disp><![CDATA[[ Ok ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ Ok ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:33]]></Time>
<TimeTick>1456396053</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="249" >
<Disp><![CDATA[[ Ok ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ Ok ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:33]]></Time>
<TimeTick>1456396053</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="251" >
<Disp><![CDATA[[ Ok ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:34]]></Time>
<TimeTick>1456396054</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="254" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ Finalize  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:35]]></Time>
<TimeTick>1456396055</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="257" >
<Disp><![CDATA[[ Finalize  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ Ok ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:35]]></Time>
<TimeTick>1456396055</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="259" >
<Disp><![CDATA[[ Ok ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ Ok ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:37]]></Time>
<TimeTick>1456396057</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="262" >
<Disp><![CDATA[[ Ok ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:43]]></Time>
<TimeTick>1456396063</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="267" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ 123, 13  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:43]]></Time>
<TimeTick>1456396063</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="269" >
<Disp><![CDATA[[ 123, 13  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:46]]></Time>
<TimeTick>1456396066</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="273" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ Finalize  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:49]]></Time>
<TimeTick>1456396069</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="276" >
<Disp><![CDATA[[ Finalize  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ Finalize  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:49]]></Time>
<TimeTick>1456396069</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="278" >
<Disp><![CDATA[[ Finalize  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ Finalize  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:52]]></Time>
<TimeTick>1456396072</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="280" >
<Disp><![CDATA[[ Finalize  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ Save  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:52]]></Time>
<TimeTick>1456396072</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="282" >
<Disp><![CDATA[[ Save  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ Close Patient Record? ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:56]]></Time>
<TimeTick>1456396076</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="285" >
<Disp><![CDATA[[ Close Patient Record? ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ Ok ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:57:56]]></Time>
<TimeTick>1456396076</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="288" >
<Disp><![CDATA[[ Ok ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/25/2016 - 15:58:03]]></Time>
<TimeTick>1456396083</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="306" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:58:06]]></Time>
<TimeTick>1456396086</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="310" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ Balse, Sewell  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:58:06]]></Time>
<TimeTick>1456396086</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="312" >
<Disp><![CDATA[[ Balse, Sewell  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:58:09]]></Time>
<TimeTick>1456396089</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="316" >
<Disp><![CDATA[[ WebElement ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ Finalize  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:58:12]]></Time>
<TimeTick>1456396092</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="319" >
<Disp><![CDATA[[ Finalize  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[[ Finalize  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/25/2016 - 15:58:12]]></Time>
<TimeTick>1456396092</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="321" >
<Disp><![CDATA[[ Finalize  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[[ Finalize  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:58:16]]></Time>
<TimeTick>1456396096</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="323" >
<Disp><![CDATA[[ Finalize  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[[ Save  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/25/2016 - 15:58:16]]></Time>
<TimeTick>1456396096</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="325" >
<Disp><![CDATA[[ Save  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[[ Close Patient Record? ].Exist]]></Obj>