<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="GREGORYJ01"><DocLocation><![CDATA[D:\PROJECT_FOLDER\Testscripts\LabTask]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[LabTask]]></DName>
<Res><![CDATA[Res4]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[12/7/2015 - 19:47:42]]></Time>
<TimeTick>1449497862</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" status="Passed" Source="Action1" SourceLine="21" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[12/7/2015 - 19:47:42]]></Time>
<TimeTick>1449497862</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Passed" Source="Action1" SourceLine="21" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[12/7/2015 - 19:47:42]]></Time>
<TimeTick>1449497862</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="21" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[12/7/2015 - 19:47:43]]></Time>
<TimeTick>1449497863</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="45" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/7/2015 - 19:47:59]]></Time>
<TimeTick>1449497879</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" >
<Disp><![CDATA[[ WebElement ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ Image ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "[ Image ]" object's parent "[ Browser ]" (class Browser). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[12/7/2015 - 19:48:00]]></Time>
<TimeTick>1449497880</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = DaVita VillageHealth Capella<br>Mercury Class = Browser<br>]]></Details>
<Time><![CDATA[12/7/2015 - 19:48:00]]></Time>
<TimeTick>1449497880</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="29" status="Warning" nType="Parent description" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="28" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ Image ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/7/2015 - 19:48:04]]></Time>
<TimeTick>1449497884</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="37" >
<Disp><![CDATA[[ WebElement ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[12/7/2015 - 19:48:04]]></Time>
<TimeTick>1449497884</TimeTick>
<NodeArgs eType="General" icon="9" nRep="38" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/7/2015 - 19:47:42" eTime="12/7/2015 - 19:48:04" passed="4" failed="1" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[LabTask Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[12/7/2015 - 19:48:04]]></Time>
<TimeTick>1449497884</TimeTick>
<NodeArgs eType="General" icon="10" nRep="41" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/7/2015 - 19:47:41" eTime="12/7/2015 - 19:48:04" passed="4" failed="1" warnings="1" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test LabTask Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>